version: "3.9"
services:
  postgres:
    image: postgres:16.2
    container_name: book-dbs
    ports: [ "5132:5432" ]
    env_file: [ .env ]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: book-kafka-zookeeper
#    platform: linux/amd64
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports: [ "22181:2181" ]
#    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: book-kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: book-kafka-ui
    platform: linux/amd64
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on: [ kafka ]
    ports: [ "29093:8080" ]
    restart: unless-stopped

  # Redis
  redis:
    container_name: book-redis
    platform: linux/amd64
    image: bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports: [ "6379:6379" ]
    networks:
      - redis-network
    env_file: [ .env ]

  redis-commander:
    container_name: book-redis-commander
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports: [ "29094:8081" ]
    networks:
      - redis-network
    env_file: [ .env ]

volumes:
  redis_data:
    driver: local
networks:
  redis-network:
    driver: bridge

